In [1]:
from datetime import datetime
import functools
from IPython.display import HTML
import jax
from jax import numpy as jp
import numpy as np
from typing import Any, Dict, Sequence, Tuple, Union
from brax import base
from brax import envs
from brax import math
from brax.base import Base, Motion, Transform
from brax.envs.base import Env, PipelineEnv, State
from brax.mjx.base import State as MjxState
# from brax.training.agents.apg import train as apg
# from brax.training.agents.apg import networks as apg_networks
from brax.io import html, mjcf, model
from etils import epath
from flax import struct
from matplotlib import pyplot as plt
import mediapy as media
from ml_collections import config_dict
import mujoco
from mujoco import mjx
from jax import vmap
import jax.random
from jax import lax

In [2]:
import distutils.util
import os
xla_flags = os.environ.get('XLA_FLAGS', '')
xla_flags += ' --xla_gpu_triton_gemm_any=True'
os.environ['XLA_FLAGS'] = xla_flags
print('Setting environment variable to use GPU rendering:')
%env MUJOCO_GL=egl

Setting environment variable to use GPU rendering:
env: MUJOCO_GL=egl


In [3]:
import os
os.environ["XLA_PYTHON_CLIENT_MEM_FRACTION"] = "0.8" # 0.9 causes too much lag. 
from datetime import datetime
import functools

# Math
import jax.numpy as jp
import numpy as np
import jax
from jax import config # Analytical gradients work much better with double precision.
config.update("jax_debug_nans", True)
config.update("jax_enable_x64", True)
config.update('jax_default_matmul_precision', jax.lax.Precision.HIGH)
from brax import math

# Sim
import mujoco
import mujoco.mjx as mjx

# Brax
from brax import envs
from brax.base import Motion, Transform
from brax.io import mjcf
from brax.envs.base import PipelineEnv, State
from brax.mjx.pipeline import _reformat_contact
from brax.training.acme import running_statistics
from brax.io import model

# Algorithms
# from brax.training.agents.apg import train as apg
# from brax.training.agents.apg import networks as apg_networks
from brax.training.agents.ppo import train as ppo

# Supporting
from etils import epath
import mediapy as media
import matplotlib.pyplot as plt
from ml_collections import config_dict
from typing import Any, Dict


In [4]:
from jax.lib import xla_bridge
print(xla_bridge.get_backend().platform)

gpu


In [5]:
import agent_mimic_env
from agent_mimic_env import register_mimic_env, register_ppo_env

In [6]:
from agent_mimic_env.pds_controllers_agents import feedback_pd_controller, stable_pd_controller_action


In [7]:
import yaml
from box import Box
# Path to your YAML file
yaml_file_path = 'config_params/punch.yaml'
# Load the YAML file
with open(yaml_file_path, 'r') as file:
    args = Box(yaml.safe_load(file))



In [8]:
print(args)

{'0.0num_envs': 256, 'num_eval_envs': 32, 'lr': 0.0003, 'max_it': 1000, 'max_grad_norm': 0.4, 'seed': 0, 'system_config': 'humanoid', 'demo_replay_mode': 'threshold', 'threshold': 0.4, 'normalize_observations': True, 'cycle_len': 130, 'ep_len': 65, 'ep_len_eval': 54, 'use_lr_scheduler': True, 'reward_scaling': 0.02, 'rot_weight': 0.5, 'vel_weight': 0.3, 'ang_weight': 0.01, 'deep_mimic_reward_weights': {'w_p': 0.65, 'w_v': 0.1, 'w_e': 0.15, 'w_c': 0.1}, 'deep_mimic_weights_factors': {'w_pose': 2, 'w_angular': 0.1, 'w_efector': 40, 'w_com': 10}, 'model': 'models/final_humanoid.xml', 'ref': 'motions/humanoid3d_punch_duplicated.txt'}


In [9]:
env_ppo = register_ppo_env(args)
env_ppo.set_pd_callback(stable_pd_controller_action)
jit_reset = jax.jit(env_ppo.reset)
#jit_step= jax.jit(env_ppo.step)
jit_step= jax.jit(env_ppo.step_custom)



this is the model:  models/final_humanoid.xml


In [10]:
#checking if doible point precision is activate
xd = jp.exp(11)
xd


Array(59874.1417152, dtype=float64, weak_type=True)

In [11]:
env_ppo.sys.link_types

'f333131313313'

In [12]:

s = env_ppo.dict_ee
print(s)

xd= env_ppo.sys.geom_pos[env_ppo.dict_ee]

xd


#right wrist idex 6 initial pos on mjx pos="0 0 -0.258947"
#left wrist inital 9 pos on mjx pos="0 0 -0.258947"
#right ankle index 12 pos [0.045   ,  0.      , -0.0225  ],
#left ankle  index 15"0.045   ,  0.      , -0.0225"

[ 6  9 12 15]


Array([[ 0.      ,  0.      , -0.258947],
       [ 0.      ,  0.      , -0.258947],
       [ 0.045   ,  0.      , -0.0225  ],
       [ 0.045   ,  0.      , -0.0225  ]], dtype=float64)

In [13]:
print(env_ppo.sys.opt)
print(env_ppo.dt)

Option(timestep=0.002, impratio=Array(100., dtype=float64, weak_type=True), tolerance=Array(1.e-08, dtype=float64, weak_type=True), ls_tolerance=Array(0.01, dtype=float64, weak_type=True), gravity=Array([ 0.  ,  0.  , -9.81], dtype=float64), wind=Array([0., 0., 0.], dtype=float64), density=Array(0., dtype=float64, weak_type=True), viscosity=Array(0., dtype=float64, weak_type=True), has_fluid_params=False, integrator=<IntegratorType.EULER: 0>, cone=<ConeType.PYRAMIDAL: 0>, jacobian=<JacobianType.AUTO: 2>, solver=<SolverType.NEWTON: 2>, iterations=1, ls_iterations=4, disableflags=<DisableBit.EULERDAMP: 16384>)
0.02


In [14]:
state = jit_reset(jax.random.PRNGKey(0))
rollout = [state.pipeline_state]

n_steps = 500

In [15]:
state.pipeline_state.qpos[:]

Array([ 1.00952578,  0.96560349,  0.763598  ,  0.69266161,  0.00396145,
        0.0290793 ,  0.72066538,  0.0344528 ,  0.38038578, -0.03930848,
        0.25575706, -0.27285779, -1.17071799, -1.60473499,  0.07730953,
       -1.0934958 ,  0.82069482,  0.59607216,  0.09617058, -0.84933419,
        1.92958378, -0.723898  , -0.63271327, -1.08916748, -1.27049323,
       -0.16462933, -0.02070159, -0.17030865,  0.37251784,  0.20128708,
        0.66214301, -0.50385212, -0.0529365 , -0.12219402, -0.05907235],      dtype=float64)

In [16]:
state.pipeline_state.geom_xpos[env_ppo.dict_ee]

Array([[1.67751076, 1.1740035 , 1.33588565],
       [0.87219029, 1.07226696, 0.94031171],
       [1.18705463, 1.14263128, 0.07462683],
       [0.71621663, 0.63931363, 0.02716332]], dtype=float64)

In [17]:
print(state.metrics)
print(state.info)

{'fall': Array(0., dtype=float64), 'pose_error': Array(0., dtype=float64), 'reference_angular': Array(0., dtype=float64, weak_type=True), 'reference_com': Array(0., dtype=float64, weak_type=True), 'reference_end_effector': Array(0., dtype=float64, weak_type=True), 'reference_quaternions': Array(0., dtype=float64, weak_type=True), 'step_index': Array(48., dtype=float64)}
{'default_pos': Array([ 1.00952578,  0.96560349,  0.763598  ,  0.69266161,  0.00396145,
        0.0290793 ,  0.72066538,  0.0344528 ,  0.38038578, -0.03930848,
        0.25575706, -0.27285779, -1.17071799, -1.60473499,  0.07730953,
       -1.0934958 ,  0.82069482,  0.59607216,  0.09617058, -0.84933419,
        1.92958378, -0.723898  , -0.63271327, -1.08916748, -1.27049323,
       -0.16462933, -0.02070159, -0.17030865,  0.37251784,  0.20128708,
        0.66214301, -0.50385212, -0.0529365 , -0.12219402, -0.05907235],      dtype=float64), 'kinematic_ref': Array([ 1.00952578,  0.96560349,  0.763598  ,  0.69266161,  0.003961

In [18]:
state.pipeline_state.subtree_com[1]

Array([1.03295954, 1.00265482, 0.82999913], dtype=float64)

In [19]:
env_ppo.rollout_lenght

65

In [20]:
for i in range(env_ppo.rollout_lenght-1):
    
    #print(i)
    ctrl = -0.1 * jp.ones(env_ppo.sys.nu)
    #time
    #time = state.pipeline_state.time
    
    #print('time: ',state.pipeline_state.time)    
         
    
    state = jit_step(state,ctrl)
    
    #print(state.pipeline_state.geom_xpos)
    #print("Is done", state.done)
    if state.done:
        print(state.pipeline_state.time)
        break
    
    print("Is rewards", state.reward)
    # print("Is quat", state.metrics['reference_quaternions'])
    # print("Is ang",state.metrics['reference_angular'])
    # print("Is ee", state.metrics['reference_end_effector'])
    # print("Is com", state.metrics['reference_com'])

    #print("reward tuple", state.info['reward_tuple'])
    #print("Is ", state.metrics['pose_error'])
    #print("Is ", state.metrics['step_index'])
    
    rollout.append(state.pipeline_state)

Is rewards 0.5795624472757559
Is rewards 0.27693716264841983
Is rewards 0.1217690837799752
Is rewards 0.06694138900997532
Is rewards 0.049133108861193785
Is rewards 0.0379649880506597
Is rewards 0.02979395816237004
Is rewards 0.022580854397952446
Is rewards 0.016875418515695045
Is rewards 0.01292788113433149
Is rewards 0.00977349656024731
Is rewards 0.007270909305261544
Is rewards 0.005375145348535982
Is rewards 0.003938136897546784
Is rewards 0.002856391218605816
Is rewards 0.002191426916286615
Is rewards 0.001619649495899163
Is rewards 0.001529105789418736
Is rewards 0.001431930520742411
Is rewards 0.0013349792589252318
Is rewards 0.0012492148652927862
Is rewards 0.0011861521557215847
Is rewards 0.0011059897374720703
Is rewards 0.0010039517898455955
Is rewards 0.000892915344486049
Is rewards 0.0007783895805671861
Is rewards 0.0006512634980970096
Is rewards 0.0005163808194914071
Is rewards 0.000388557865842425
Is rewards 0.00027565392034268514
Is rewards 0.0001825721359005117
Is rewar

In [21]:
from some_math.rotation6D import quaternion_to_rotation_6d

In [61]:
#coputing the formulas.
def com_reward(com_current, ref_com):
    
    print(com_current.shape)
    #compute over the rows
    com_dist = jp.sum(jp.linalg.norm(com_current - ref_com, axis=-1))         
    print(com_dist)
    
    com_reward = jp.exp(-100 * (com_dist))
    
    return com_reward

def end_effector_diff(current_ee,current_ref_ee):
    # jax.debug.print("end diff result local:{}",current_ee)
    # jax.debug.print("end diff result ref:{}",current_ref_ee)        
    ee_dist = jp.linalg.norm(current_ee - current_ref_ee,axis=1)   
    
    print(ee_dist.shape)
    
    ee_dist = jp.sum(ee_dist)     
    print(ee_dist)
    
    #jax.debug.print("end dis:{}",ee_dist)
    ee_reward = jp.exp(- 5 * (ee_dist))
    #jax.debug.print("ee_reward:{}",ee_reward)
    
    return ee_reward
    
def angular_diff(local_ang,ref_local_ang):
        
        # jax.debug.print("ang diff result local:{}",local_ang)
        # jax.debug.print("ang diff result ref:{}",ref_local_ang)
        
        ang_norm = jp.linalg.norm(ref_local_ang - local_ang,ord=2,axis=-1)
        print(ang_norm)
        ang_dist = jp.sum(ang_norm**2)
        #ang_reward = jp.exp(-0.1* ang_dist)
        
        return ang_dist
        





In [64]:
xd = jp.array([2,3,4,5])
xd1 = jp.array([12,33,24,25])


diff = angular_diff(xd,xd1)


42.42640687119285


In [23]:
def quat_mul(u: jax.Array, v: jax.Array) -> jax.Array:
  """Multiplies two quaternions.

  Args:
    u: (4,) quaternion (w,x,y,z)
    v: (4,) quaternion (w,x,y,z)

  Returns:
    A quaternion u * v.
  """
  return jp.array([
      u[0] * v[0] - u[1] * v[1] - u[2] * v[2] - u[3] * v[3],
      u[0] * v[1] + u[1] * v[0] + u[2] * v[3] - u[3] * v[2],
      u[0] * v[2] - u[1] * v[3] + u[2] * v[0] + u[3] * v[1],
      u[0] * v[3] + u[1] * v[2] - u[2] * v[1] + u[3] * v[0],
  ])






In [24]:
ref_rotation = jp.array([
    [ 0.66902921,  0.00306604,  0.02550548,  0.74279202],
    [ 0.98153105,  0.01574312,  0.18995663, -0.0162921 ],
    [ 0.80401407,  0.18448749, -0.0462765,  -0.56336865],
    [ 0.56897937, -0.66876529, -0.33338603, -0.34332088],
    [ 0.95711128,  0.        , -0.28972054,  0.        ],
    [ 0.8763031 ,  0.25212639,  0.20668992, -0.3546892 ],
    [ 0.5970678 ,  0.        , -0.80219078,  0.        ],
    [ 0.83085447, -0.16544382, -0.42532115, -0.31845112],
    [ 0.79358915, -0.        ,  0.60845399, -0.        ],
    [ 0.99900294, -0.03151216,  0.0052796,  -0.03118084],
    [ 0.9268976 ,  0.21245762, -0.00543069,  0.30934302],
    [ 0.95786436, -0.        ,  0.28722093, -0.        ],
    [ 0.99531659, -0.02673809, -0.0872572,  -0.03187685]
])

# Global rotation matrix
global_rotation = jp.array([
    [ 1.        ,  0.        ,  0.        ,  0.        ],
    [ 0.66902921,  0.00306604,  0.02550548,  0.74279202],
    [ 0.66388138, -0.12797178,  0.16386477,  0.71835442],
    [ 0.96966061, -0.03948665,  0.16145958,  0.17924818],
    [ 0.59340802, -0.333563  , -0.65243899,  0.33305558],
    [ 0.37893253, -0.22276386, -0.79637921,  0.4154113 ],
    [ 0.83494974, -0.15135773,  0.4165387 ,  0.32625954],
    [ 0.8326651 ,  0.17135156, -0.42108714,  0.31621684],
    [ 0.80376414,  0.19966359, -0.38527489,  0.40701463],
    [ 0.87228055, -0.08919882,  0.18330353,  0.44448851],
    [ 0.88149174, -0.1246596 ,  0.17093797,  0.42215223],
    [ 0.38983116,  0.15690608,  0.17687105,  0.89001617],
    [ 0.32260431, -0.10533653,  0.28138614,  0.89758148],
    [ 0.37144196, -0.04411828,  0.22456133,  0.89980923]
])


#it works well my local joints in joint space
chest = ref_rotation[1]
root = global_rotation[1]
right_shoulder = ref_rotation[3]

global_chest = quat_mul(root,chest)
global_right = quat_mul(global_chest,right_shoulder)

print(global_right)



[ 0.59340802 -0.333563   -0.65243899  0.33305558]


In [25]:
#test the one dofs joints
joint_right_elbow = ref_rotation[4]
global_right_elbow = quat_mul(global_right,joint_right_elbow)
print(global_right_elbow)

[ 0.37893253 -0.22276387 -0.79637921  0.41541131]


Testing rewards

In [26]:
HTML(html.render(env_ppo.sys.tree_replace({'opt.timestep': env_ppo.dt}), rollout))